In [1]:
import numpy as np

# Вкладчик положил 50000 условных единиц на три разных счета в три разных банка. По первому счету выплаты составят 5%
# годовых, по второму – 7% годовых и по третьему 6% годовых. Известно, что через год вкладчик получил по процентам
# сумму в 2250 у.е. с первого и второго банка и сумму в 1400 у.е. с первого и третьего банка. Сколько условных единиц
# он положил на каждый счет изначально?


A = np.array([[0.05, 0.07, 0], [0.05, 0, 0.06], [1, 1, 1]])
b = np.array([2250, 1400, 50000])
A_inv = np.linalg.inv(A)
A_inv.dot(b)

array([10000., 25000., 15000.])

In [2]:
#На складе хранятся мобильные телефоны iPhone 6, iPhone 11, iPhone 12 моделей. Всего 1328 экземпляра. Моделей iPhone 6
# на 120 меньше, чем моделей iPhone 11, и на 100 больше, чем моделей iPhone 12. Сколько моделей каждого вида на складе?

A = np.array([[1, 1, 1], [-1, 1, 0], [1, 0, -1]])
b = np.array([1328, 120, 100])
A_inv = np.linalg.inv(A)
A_inv.dot(b)

array([436., 556., 336.])

In [7]:
# Составьте каноническое уравнение эллипсоида, проходящего через три точки A,B,C

A = np.array([[3, 0, 3], [6, 1/4, 0], [1, 1/3, 1]])
b = np.array([1, 1, 1])
A_inv = np.linalg.inv(A)
x = A_inv.dot(b)
fin = []
for i in x:
    fin.append([1/np.sqrt(i), -1/np.sqrt(i)])
fin


[[3.4641016151377553, -3.4641016151377553],
 [0.7071067811865475, -0.7071067811865475],
 [2.0000000000000004, -2.0000000000000004]]

In [4]:
# Составьте уравнение параболы проходящей через заданные три точки (1,12), (3,54), (-1,2).
# Необходимо найти коэффициенты уравнения a,b,ca,b,c

A = np.array([[1, 1, 1], [9, 3, 1], [1, -1, 1]])
b = np.array([12, 54, 2])
A_inv = np.linalg.inv(A)
A_inv.dot(b)

array([4., 5., 3.])

In [5]:
# Составьте функцию get_polynom

def get_polynom(coords):
    b = np.array([])
    a_lists = []
    for x, y in coords:
        x_list = []
        for i in range(len(coords)):
            x_list.append(x ** i)
        a_lists.append(x_list[::-1])
        b = np.append(b, y)
    a = np.array(a_lists)
    return np.linalg.solve(a, b)
get_polynom([(1, 12), (3, 54), (-1, 2)])

array([4., 5., 3.])